version: "3.7"
services:
  web1:
    build: ./quote_gen
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "5001:5001"
    volumes:
      - app_data1:/app

  web2:
    build: ./quote_disp
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - "5002:5002"
    volumes:
      - app_data2:/app
    depends_on:
      - web1

volumes:
  app_data1:
  app_data2: